version: "2"
run:
  timeout: 10m
  issues-exit-code: 1
  tests: false
  allow-parallel-runners: true
output:
  formats:
    junit-xml:
      path: golangci-lint.xml
  stdout:
    format: colored-line-number
  path-prefix: ""
linters:
  enable:
    - bodyclose
    - exhaustive
    - forbidigo
    - gocritic
    - mirror
    - misspell
    - nilerr
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unparam
    - unused
  settings:
    exhaustive:
      explicit-exhaustive-switch: true
    forbidigo:
      forbid:
        - pattern: ioutil\.ReadDir
          msg: Please use os\.ReadDir instead
        - pattern: errors\.New\(fmt\.Sprintf
          msg: Please use errors.Errorf instead
        - pattern: sort\.Slice
          msg: Please use slices\.SortFunc instead
        - pattern: sort\.SliceStable
          msg: Please use slices\.SortStableFunc instead
        - pattern: sort\.SliceIsSorted
          msg: Please use slices\.IsSortedFunc instead
        - pattern: sort\.Strings
          msg: Please use slices\.Sort instead
        - pattern: sort\.Ints
          msg: Please use slices\.Sort instead
    gocritic:
      disabled-checks:
        - ifElseChain
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
      settings:
        printf:
          funcs:
            - common.Errorf
    revive:
      enable-all-rules: false
      # 使用 allow-list 模式：只启用下面显式列出的规则
      # 这是更安全、可控的策略，但需要逐步完善启用的规则集合
      rules:
        - name: unhandled-error
        - name: indent-error-flow
        - name: var-naming
        - name: error-naming
        - name: exported
        - name: errorf
        - name: bare-return
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Rollback
      - path: (.+)\.go$
        text: logger.Sync
      - path: (.+)\.go$
        text: pgInstance.Stop
      - path: (.+)\.go$
        text: fmt.Printf
      - path: (.+)\.go$
        text: Enter(.*)_(.*)
      - path: (.+)\.go$
        text: Exit(.*)_(.*)
      - path: (.+)\.go$
        text: DB
    paths:
      - config
      - docker
      - certificate
      - hooks
      - swagger
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  whole-files: true
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - yunqutech.gitlab.com
  exclusions:
    generated: lax
    paths:
      - config
      - docker
      - certificate
      - hooks
      - swagger
      - third_party$
      - builtin$
      - examples$
